# syntax=docker/dockerfile:1

#FROM golang:1.19-alpine3.16
FROM golang

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

ENTRYPOINT [ "/bin/sh" ]
# ENTRYPOINT [ "/go/bin/dlv", "debug", "cmd/api/main.go" ]
