# syntax=docker/dockerfile:1

FROM golang:1.16-buster AS build

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.8

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

ENTRYPOINT [ "bash" ]
# ENTRYPOINT [ "/go/bin/dlv", "debug", "cmd/api/main.go" ]
