# syntax=docker/dockerfile:1

## Build
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/boredgames-build cmd/api/main.go

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/bin/boredgames-build /boredgames
COPY --from=build /app/ui /ui

EXPOSE 8080

ENTRYPOINT ["/boredgames"]
