# syntax=docker/dockerfile:1

## Build
FROM golang:1.19-alpine3.16 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o /boredgames cmd/api

## Deploy
FROM alpine:3.16

WORKDIR /

COPY --from=build /boredgames /boredgames
COPY --from=build /app/ui /ui

EXPOSE 8080

ENTRYPOINT ["/boredgames"]
