// Code generated by "stringer -type=Color"; DO NOT EDIT.

package set

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-0]
	_ = x[Purple-1]
	_ = x[Green-2]
}

const _Color_name = "RedPurpleGreen"

var _Color_index = [...]uint8{0, 3, 9, 14}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
