// Code generated by "stringer -type=Shape"; DO NOT EDIT.

package set

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Oval-0]
	_ = x[Triangle-1]
	_ = x[Squiggle-2]
}

const _Shape_name = "OvalTriangleSquiggle"

var _Shape_index = [...]uint8{0, 4, 12, 20}

func (i Shape) String() string {
	if i >= Shape(len(_Shape_index)-1) {
		return "Shape(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Shape_name[_Shape_index[i]:_Shape_index[i+1]]
}
